### ISSUE TITLE
Chaining check causes duplicated errors

### ISSUE THREAD

**Issue by muka** [ctavan/express-validator#30]
`request.check('email', 'Email is not valid').notEmpty().notNull().isEmail();`

With no "email" field set this will return 3 repeatitions of the same message. 
Shouldn't the error message be unified on chained call like this?

Thank you

**Comment by aselivanov** [comment]
Please merge! :-)

**Comment by slier81** [comment]
So how was it? merged?

**Comment by Joshua-F** [comment]
Any updates?

**Comment by rustybailey** [comment]
I will look into this. The only issue is that it would require a major version update since it would break all unit tests (not to mention people's existing code in the wild). I won't be able to touch it this weekend, but I'll try to get to it this week.

**Comment by Joshua-F** [comment]
Would there be an issue by adding it as an option in the middleware options?

**Comment by rustybailey** [comment]
That could work. 

Thanks,
Rusty Bailey

**Comment by elkebirmed** [comment]
This one should be fixed ASAP guys!

**Comment by utdrmac** [comment]
+1 Please merge. To make it backwards compatible and not break existing installations, turn this into an option with the default being current behavior.

**Comment by christophedebatz** [comment]
Hi, did you merge this fix? It's very important...

**Comment by Jovaage** [comment]
Has there been made any progress on this 3 year old issue?

I still get duplicate error messages when chaining, and I can't find anything in the docs about preventing it by passing in anything in the middleware options.

**Comment by TheHominid** [comment]
I don't really see this as a breaking change for existing code out there, as we could just ad an additional option when attaching express validator to the app to tell if we want to have duplicate errors or not.
What do you think?

**Comment by gustavohenke** [comment]
Hi @TheHominid. I'm glad that you found something that works for you at the moment.

Anyway, with the introduction of #269, it's easy to add opt-in support to new methods that fix issues like this.
That's my plan, so this issue can finally be closed.

**Comment by gustavohenke** [comment]
Hi everyone! The fix for this has finally landed in v3.0.0!

```js
req.getValidationResult().then( result => {
  var errors = result.useFirstErrorOnly().array(); // enjoy an array with no duplicated errors for any given parameter!
})
```

**Comment by gustavohenke** [comment]
@Hassaan-Ahmed please open a new issue with detailed information.

**Comment by HighSoftWare96** [comment]
Is there a way to achieve this with the `validationResult()` method? Like this:
```
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
      errors.useFirstErrorOnly().array()
  }
```

**Comment by gustavohenke** [comment]
Yes, you can use `errors.array({ onlyFirstError: true })`. See docs [here](https://express-validator.github.io/docs/validation-result-api.html#array-options).

Please open a new issue if you still face problems.
